config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings as setting, settings
from core.home.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('inicio/', include('core.inicio.urls')),
    path('login/', include('core.login.urls')),
    path('company/', include('core.company.urls')),
    path('products/', include('core.products.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

core/company/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from core.company.views import CompanyCreateView, CompanyUpdateView, CompanyListView


app_name = 'company'

urlpatterns = [
    path('add/', CompanyCreateView.as_view(), name='company_create'),
    path('update/<int:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    path('list/', CompanyListView.as_view(), name='company_list'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/inicio/urls.py
from django.urls import path
from core.inicio.views import *

app_name = 'inicio'

urlpatterns = [
    path('', InicioView.as_view(), name='inicio'),
    path('inicio/notperms/', NotPermsView.as_view(), name='notperms'),
]

core/products/urls.py
from django.conf.urls.static import static
from django.urls import path

from config import settings
from core.products.views import *

app_name = 'products'

urlpatterns = [
    path('add/', ProductCreateView.as_view(), name='product_create'),
    path('list/', ProductListView.as_view(), name='product_list'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.urls import path
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('update-password/<int:pk>/', UserPasswordUpdateView.as_view(), name='user_password_update'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/', MyProfileDetailView.as_view(), name='user_profile'),
    path('profile/edit/<int:pk>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
    # path('register/', registerview, name='account_create')
]

core/home/models.py
from django.db import models

# Create your models here.

core/home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'BPMPro Estabilidades'
        return context

class SinpermisosView(TemplateView):
    # template_name = 'sinpermisos.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Sin Permisos de Acceso'
        return context

templates/body.html
{% extends 'home.html' %}
{% load static %}

{% block body %}

    <div class="wrapper">
        {% include 'sidebar.html' %}

        <div class="main-panel">

            {% include 'header.html' %}

            <div class="content">
                <div class="content">
                    <div class="container-fluid">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-with-icon">
                                    <i class="material-icons" data-notify="icon">
                                        {% if message.tags == 'success' %}
                                            check
                                        {% elif message.tags == 'warning' %}
                                            warning
                                        {% else %}
                                            error_outline
                                        {% endif %}
                                    </i>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">x
                                    </button>
                                    <span id="message" class="msg" data-notify="message">
                                            {% if message.tags == 'success' %}
                                                <b>Exito:</b>
                                            {% elif message.tags == 'warning' %}
                                                <b>Precaución:</b>
                                            {% else %}
                                                <b>Error:</b>
                                            {% endif %}
                                        {{ message }}
                                        </span>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="row">
                            {% block content %}

                            {% endblock %}

                            {% block not_perms %}

                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'footer.html' %}
        </div>
    </div>

    <!--   Core JS Files   -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/core/jquery.min.js' %}"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/core/bootstrap-material-design.min.js' %}"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
    <!-- Plugin for the momentJs  -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/moment.min.js' %}"></script>
    <!--  Plugin for Sweet Alert -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/sweetalert2.js' %}"></script>
    <!-- Forms Validations Plugin -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/jquery.validate.min.js' %}"></script>
    <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/jquery.bootstrap-wizard.js' %}"></script>
    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/bootstrap-selectpicker.js' %}"></script>
    <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
    <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/jquery.dataTables.min.js' %}"></script>
    <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/bootstrap-tagsinput.js' %}"></script>
    <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/jasny-bootstrap.min.js' %}"></script>
    <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/fullcalendar.min.js' %}"></script>
    <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/jquery-jvectormap.js' %}"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/nouislider.min.js' %}"></script>
    <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
    <!-- Library for adding dinamically elements -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/arrive.min.js' %}"></script>
    <!-- Chartist JS -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/chartist.min.js' %}"></script>
    <!--  Notifications Plugin    -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/bootstrap-notify.js' %}"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/material-dashboard.js' %}"
            type="text/javascript"></script>

    <script>
        let elem = document.getElementById('message');
        if (elem) {
            let errorsList = document.querySelectorAll('.msg > .errorlist > li > ul > li');
            if (errorsList.length > 0) {
                elem.innerHTML = "";
                errorsList.forEach(li => elem.appendChild(li))
            }
        }
    </script>

    {% block javascript %}

    {% endblock %}

{% endblock %}

templates/footer.html
{% load static %}

<footer class="footer">
    <div class="container-fluid">
        <div class="copyright float-right">
            &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>
            , made with <i class="material-icons">favorite</i> by
            <a href="https://www.cieltechno.com" target="_blank">CielTechno SAS,</a> BPMPRO Quality Control v1.0.
        </div>
    </div>
</footer>

templates/form.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/core/jquery.min.js' %}"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/material-dashboard.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/moment.min.js' %}"></script>
    <script src="{% static 'lib/moment-es/es.js' %}"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="col-md-12">
        <form enctype="multipart/form-data" action="" method="post">
            <div class="card">
                {% block card_header %}

                {% endblock %}
                <div class="card-body">
                    <div class="form-group">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="{{ action }}">
                        {% for field in form.visible_fields %}
                            {% if forloop.first %}
                                <div class="row">
                            {% endif %}
                        <div class="col-md-4">
                            <div {% if field.name == 'is_active' %} class="checkbox"
                            {% elif field.name == 'photo' or field.name == 'companyLogo' %}
                                                                    class="fileinput fileinput-new text-center"
                                                                    data-provides='fileinput'
                            {% else %} class="form-group label-floating" {% endif %}>
                                {% if field.name == 'is_active' %}
                                    <label>
                                        {{ field }}
                                        {{ field.label }}
                                    </label>
                                {% elif field.name == 'photo' or field.name == 'companyLogo' %}
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                    <span class="btn btn-rose btn-round btn-file">
                                        <span class="fileinput-new">Selecionar imagen</span>
                                        <span class="fileinput-exists">Cambiar</span>
                                        {{ field }}
                                    </span>
                                        <a href="#" class="btn btn-danger btn-round fileinput-exists"
                                           data-dismiss="fileinput"><i class="fa fa-times"></i> Eliminar</a>
                                    </div>
                                {% else %}
                                    <label class="control-label" for=id_{{ field.name }}">
                                        {{ field.label }}
                                    </label>
                                    {{ field }}
                                {% endif %}
                                {% if field.help_text %}
                                    <span class="form-text text-muted">{{ field.help_text }}</span>
                                {% endif %}
                            </div>
                        </div>
                        {% if forloop.last %}
                            </div>
                        {% elif forloop.counter|divisibleby:3 %}
                            </div>
                            <div class="row">
                        {% endif %}
                        {% endfor %}
                        </div>
                    </div>
                <div class="card-footer ml-auto mr-auto">
                    <button type="submit" class="btn btn-success">
                        <i class="material-icons">check</i>
                        Guardar
                    </button>
                    <a href="{{ list_url }}" class="btn btn-danger btn-fill">
                        <i class="material-icons">close</i>
                        Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>

    <script type="text/javascript">
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });
        $('#date_birth').datetimepicker({
            format: 'YYYY-MM-DD',
            locale: 'es',
            defaultDate: $('.date_birth'),
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove',
            },
        });
    </script>
{% endblock %}

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                    <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <a class="navbar-brand" href="javascript:;"><b>{{ company }}</b></a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="javascript:;">
                        <i class="material-icons">dashboard</i>
                        <p class="d-lg-none d-md-block">
                            Stats
                        </p>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                        <a class="dropdown-item" href="#">You have 5 new tasks</a>
                        <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                        <a class="dropdown-item" href="#">Another Notification</a>
                        <a class="dropdown-item" href="#">Another One</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/home.html
<!--
=========================================================
Material Dashboard PRO - v2.2.2
=========================================================

Product Page: https://www.creative-tim.com/product/material-dashboard-pro
Copyright 2020 Creative Tim (https://www.creative-tim.com)
Coded by Creative Tim

=========================================================
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8"/>
    <link rel="apple-touch-icon" sizes="76x76"
          href="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png"
          href="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/img/favicon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>
        {{ title }}
    </title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport'/>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/css/material-dashboard.css' %}"
          rel="stylesheet"/>

    {% block head %}

    {% endblock %}
</head>


<body class="">

    {% block body %}

    {% endblock %}

</body>

</html>

templates/index.html
{% extends 'body.html' %}

templates/notperms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/sidebar.html
{% load static %}

<div class="sidebar" data-color="rose" data-background-color="black"
     data-image="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/img/sidebar-1.jpg' %}">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
    <div class="logo">
        <a class="simple-text logo-mini" href="#">
            <img src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/img/favicon.png' %}"
                 style="max-width: 80%;max-height: 80%;width:auto;height:auto" alt="logo_bpmpro_favicon"/>
        </a>
        <a class="simple-text logo-normal" href="#">
            <img src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/img/logo_bpm_pro_white.png' %}"
                 style="max-width: 90%;max-height: 90%;width:auto;height:auto" alt="logo_bpmpro"/>
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                {% if request.user.photo %}
                    <img src="{{ request.user.photo.url }}" alt="logo"/>
                {% else %}
                    <img src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/img/default-avatar.png' %}"
                         alt="photo_user"/>
                {% endif %}
            </div>
            <div class="user-info">
                <a data-toggle="collapse" href="#collapseExample" class="username">
              <span>
                {{ request.user.get_full_name }}
                <b class="caret"></b>
              </span>
                </a>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:user_profile' request.user.id %}">
                                <span class="sidebar-mini"> MP </span>
                                <span class="sidebar-normal"> Mi Perfil </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">
                                <span class="sidebar-mini"> CS </span>
                                <span class="sidebar-normal"> Cerrar Sesión </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <ul class="nav">
            {% url 'inicio:inicio' as inicio %}
            {% url 'user:user_list' as user_list %}
            {% url 'user:user_create' as user_create %}
            {% url 'company:company_create' as company_create %}
            {% url 'company:company_list' as company_list %}
            {% url 'products:product_create' as product_create %}
            {% url 'products:product_list' as product_list %}

            <li class="nav-item {% if inicio in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'inicio:inicio' %}">
                    <i class="material-icons">home</i>
                    <p> Inicio </p>
                </a>
            </li>
            <li class="nav-item {% if product_list in request.path or product_create in request.path %} active {% endif %}">
                <a class="nav-link" data-toggle="collapse" href="#products">
                    <i class="material-icons">inventory_2</i>
                    <p> Productos
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse {% if product_list in request.path or product_create in request.path %} show {% endif %}"
                     id="products">
                    <ul class="nav">
                        <li class="nav-item {% if product_list in request.path %} active {% endif %}">
                            <a class="nav-link" href="{% url 'products:product_list' %}">
                                <span class="sidebar-mini"> LP </span>
                                <span class="sidebar-normal"> Lista Productos </span>
                            </a>
                        </li>
                        <li class="nav-item {% if product_create in request.path %} active {% endif %}">
                            <a class="nav-link" href="{% url 'products:product_create' %}">
                                <span class="sidebar-mini"> CP </span>
                                <span class="sidebar-normal"> Crear Producto </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item {% if user_list in request.path or user_create in request.path %} active {% endif %}">
                <a class="nav-link" data-toggle="collapse" href="#manageUsers">
                    <i class="material-icons">manage_accounts</i>
                    <p> Gestión Usuarios
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse {% if user_list in request.path or user_create in request.path %} show {% endif %}"
                     id="manageUsers">
                    <ul class="nav">
                        <li class="nav-item {% if user_list in request.path %} active {% endif %}">
                            <a class="nav-link" href="{% url 'user:user_list' %}">
                                <span class="sidebar-mini"> LU </span>
                                <span class="sidebar-normal"> Lista Usuarios </span>
                            </a>
                        </li>
                        <li class="nav-item {% if user_create in request.path %} active {% endif %}">
                            <a class="nav-link" href="{% url 'user:user_create' %}">
                                <span class="sidebar-mini"> CU </span>
                                <span class="sidebar-normal"> Crear Usuario </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item {% if company_create in request.path or company_list in request.path %} active {% endif %}">
                <a class="nav-link" data-toggle="collapse" href="#company">
                    <i class="material-icons">settings</i>
                    <p> Compañia
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse {% if company_create in request.path or company_list in request.path %} show {% endif %}"
                     id="company">
                    <ul class="nav">
                        <li class="nav-item {% if company_create in request.path or company_list in request.path %} active {% endif %}">
                            <a class="nav-link" {% if company >= 1 %}
                               href="{% url 'company:company_list' %}" {% else %} href="{% url 'company:company_create' %} {% endif %}">
                                <span class="sidebar-mini"> CF </span>
                                <span class="sidebar-normal"> Configuración </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <div class="sidebar-background"></div>
</div>