config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings as setting, settings
from core.home.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('inicio/', include('core.inicio.urls')),
    path('login/', include('core.login.urls')),
    path('company/', include('core.company.urls')),
    path('products/', include('core.products.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

core/user/urls.py
from django.urls import path
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('update-password/<int:pk>/', UserPasswordUpdateView.as_view(), name='user_password_update'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/', MyProfileDetailView.as_view(), name='user_profile'),
    path('profile/edit/<int:pk>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
    # path('register/', registerview, name='account_create')
]

core/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# from django.forms import model_to_dict

from config.settings import MEDIA_URL, STATIC_URL


class User(AbstractUser):
    cedula = models.CharField(max_length=15, null=True, blank=True, unique=False, verbose_name='Cédula')
    cargo = models.CharField(max_length=50, null=True, blank=True, verbose_name='Cargo')
    email_person = models.EmailField(null=True, blank=True, verbose_name='Email Personal')
    cellphone = models.CharField(max_length=10, null=True, blank=True, verbose_name='N° Celular')
    address_user = models.CharField(max_length=50, null=True, blank=True, verbose_name='Dirección')
    date_birth = models.DateField(null=True, blank=True, verbose_name='Fecha de Nacimiento')
    photo = models.ImageField(upload_to='user/%Y%m%d', null=True, blank=True, verbose_name='Foto')

    def __str__(self):
        return f'{self.get_full_name()}, {self.cargo}'

    def get_image(self):
        if self.photo:
            return '{}{}'.format(MEDIA_URL, self.photo)
        return '{}{}'.format(STATIC_URL, 'img/default-avatar.png')

    # def tojson(self):
    #     item = model_to_dict(self, exclude=['password', 'user_permissions'])
    #     if self.last_login:
    #         item['last_login'] = self.last_login.strftime('%Y-%m-%d %H:%M')
    #     item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
    #     item['full_name'] = self.get_full_name()
    #     item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
    #     return item

core/user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, UpdateView, DetailView, FormView

from core.user.forms import *
from core.user.models import User

# Creacion de usuario
class UserCreateView(LoginRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'create.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.add_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    name_username = form.cleaned_data.get('username')
                    messages.success(request, f'Usuario "{name_username}" creado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de Usuarios'
        context['list_url'] = reverse_lazy('user:user_list')
        context['action'] = 'add'
        context['entity'] = 'Creación Usuario'
        return context

# Listado de usuarios
class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'list_user.html'
    # permission_required = 'user.view_user'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                usuarios = list(User.objects.values(
                    'id',
                    'date_joined',
                    'last_login',
                    'cedula',
                    'username',
                    'cargo',
                    'groups__name',
                    'email',
                    'is_active',
                    'first_name',
                    'last_name'
                ).filter(is_superuser=False).order_by('first_name'))
                return JsonResponse(usuarios, safe=False)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Usuarios'
        context['create_url'] = reverse_lazy('user:user_create')
        context['list_url'] = reverse_lazy('user:user_list')
        context['entity'] = 'Usuarios'
        return context

# Edicion de usuario por Administrador
class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'create.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    name_username = form.cleaned_data.get('username')
                    messages.success(request, f'Usuario "{name_username}" actualizado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de Usuarios'
        context['list_url'] = reverse_lazy('user:user_list')
        context['entity'] = 'Editar Usuario'
        context['action'] = 'edit'
        context['users'] = User.objects.all()
        return context

# Detalle de Usuario
class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'detail.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(UserDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Perfil de Usuario'
        context['entity'] = 'Perfil de Usuario'
        context['list_url'] = reverse_lazy('user:user_list')
        return context

# Detalle de Perfil de usuario logueado
class MyProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'profile.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(MyProfileDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mi Perfil'
        context['entity'] = 'Mi Perfil'
        context['list_url'] = reverse_lazy('inicio:inicio')
        return context

# Edicion de perfil por usuario logueado
class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileUpdateForm
    template_name = 'create.html'
    success_url = reverse_lazy('inicio:inicio')
    # permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    messages.success(request, f'Su perfil ha sido actualizado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Perfil'
        context['list_url'] = reverse_lazy('user:user_profile', kwargs={'pk': self.kwargs.get('pk')})
        context['entity'] = 'Editar Perfil'
        context['action'] = 'edit'
        return context

# Reseteo de contraseña por administrador
class UserPasswordUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserPasswordUpdateForm
    template_name = 'create.html'
    success_url = reverse_lazy('user:user_list')
    # permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    messages.success(request, f'Contraseña de usuario reseteada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reseteo de Contraseña'
        context['list_url'] = reverse_lazy('user:user_list')
        context['entity'] = 'Reseteo de Contraseña de Usuario'
        context['action'] = 'edit'
        return context

# Cambio de contraseña por usuario
class UserChangePasswordView(LoginRequiredMixin, FormView):
    model = User
    form_class = PasswordChangeForm
    template_name = 'create.html'
    success_url = reverse_lazy('user:change_password')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        form = PasswordChangeForm(user=self.request.user)
        form.fields['old_password'].widget.attrs['class'] = 'form-control'
        form.fields['new_password1'].widget.attrs['class'] = 'form-control'

core/user/templates/create.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/core/jquery.min.js' %}"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/material-dashboard.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/moment.min.js' %}"></script>
    <script src="{% static 'lib/moment-es/es.js' %}"></script>
    <script src="{% static 'lib/material-dashboard-pro-html-v2.2.2/assets/js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="col-md-12">
        <form enctype="multipart/form-data" action="" method="post">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon">
                        {% if action == 'add' %}
                            <i class="material-icons">person_add</i>
                        {% elif action == 'edit' %}
                            <i class="material-icons">person</i>
                        {% elif entity == 'Reseteo de Contraseña de Usuario' or 'Cambiar Contraseña' %}
                            <i class="material-icons">lock</i>
                        {% else %}
                            <i class="material-icons">edit</i>
                        {% endif %}
                    </div>
                    <h4 class="card-title" style="font-weight: bold">{{ entity }}</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="{{ action }}">
                        {% for field in form.visible_fields %}
                            {% if forloop.first %}
                                <div class="row">
                            {% endif %}
                        <div class="col-md-4">
                            <div {% if field.name == 'is_active' %} class="checkbox"
                            {% elif field.name == 'photo' or field.name == 'companyLogo' %}
                                                                    class="fileinput fileinput-new text-center"
                                                                    data-provides='fileinput'
                            {% else %} class="form-group label-floating" {% endif %}>
                                {% if field.name == 'is_active' %}
                                    <label>
                                        {{ field }}
                                        {{ field.label }}
                                    </label>
                                {% elif field.name == 'photo' or field.name == 'companyLogo' %}
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                    <span class="btn btn-rose btn-round btn-file">
                                        <span class="fileinput-new">Selecionar imagen</span>
                                        <span class="fileinput-exists">Cambiar</span>
                                        {{ field }}
                                    </span>
                                        <a href="#" class="btn btn-danger btn-round fileinput-exists"
                                           data-dismiss="fileinput"><i class="fa fa-times"></i> Eliminar</a>
                                    </div>
                                {% else %}
                                    <label class="control-label" for=id_{{ field.name }}">
                                        {{ field.label }}
                                    </label>
                                    {{ field }}
                                {% endif %}
                                {% if field.help_text %}
                                    <span class="form-text text-muted">{{ field.help_text }}</span>
                                {% endif %}
                            </div>
                        </div>
                        {% if forloop.last %}
                            </div>
                        {% elif forloop.counter|divisibleby:3 %}
                            </div>
                            <div class="row">
                        {% endif %}
                        {% endfor %}
                        </div>
                    </div>
                <div class="card-footer ml-auto mr-auto">
                    <button type="submit" class="btn btn-success">
                        <i class="material-icons">check</i>
                        Guardar
                    </button>
                    <a href="{{ list_url }}" class="btn btn-danger btn-fill">
                        <i class="material-icons">close</i>
                        Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>

    <script type="text/javascript">
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });
        $('#date_birth').datetimepicker({
            format: 'YYYY-MM-DD',
            locale: 'es',
            defaultDate: $('.date_birth'),
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove',
            },
        });
    </script>
{% endblock %}

core/user/templates/detail.html
{% extends 'body.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
    <script src="{% static 'lib/materialkitpro/js/jquery-3.1.1.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="col-md-9">
        <div class="card">
            <div class="card-header card-header-icon" data-background-color="rose">
                <i class="material-icons">assignment_ind</i>
            </div>
            <div class="card-content">
                <h4 class="card-title" style="font-weight: bold">{{ entity }} - {{ object.username }}</h4>
                    <div class="card-content">
                        <div class="row">
                            <div class="col-md-4">
                                <p class="card-text"><strong>N° Identificación:</strong></p>{{ object.cedula }}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>N° Celular:</strong></p>{{ object.cellphone }}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>E-mail:</strong></p>{{ object.email }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-4">
                                <p class="card-text"><strong>E-mail Personal:</strong></p>
                                {% if object.email_person == None %}
                                    Sin Registro
                                {% else %}
                                    {{ object.email_person }}
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>Fecha de Nacimiento:</strong></p>
                                {% if object.date_birth == None %}
                                    Sin Registro
                                {% else %}
                                    {{ object.date_birth}}
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>Dirección:</strong></p>
                                {% if object.address_user == None %}
                                    Sin Registro
                                {% else %}
                                    {{ object.address_user }}
                                {% endif %}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-4">
                                <p class="card-text"><strong>Fecha de Creación:</strong></p>{{ object.date_joined | date:'Y-m-d' }}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>Ultima Sesión:</strong></p>
                                {% if object.last_login == None %}
                                    Sin Registro de Ingreso
                                {% else %}
                                    {{ object.last_login | date:'Y-m-d H:m'}}
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <a href="{% url 'user:user_password_update' object.id %}" class="btn btn-rose btn-round">Resetear Contraseña</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card card-profile">
            <div class="card-avatar">
                <a href="#">
                    {% if user.photo %}
                        <img class="img" src="{{ user.photo.url }}" alt="bpmpro_user"/>
                    {% else %}
                        <img class="img" src="{% static 'lib/materialkitpro/img/../../../static/lib/material-dashboard-pro-html-v2.2.2/assets/img/default-avatar.png' %}" alt="bpmpro_user"/>
                    {% endif %}
                </a>
            </div>
            <div class="card-content">
                <h6 class="category text-gray">{{ object.cargo }}</h6>
                <h4 class="card-title">{{ object.get_full_name }}</h4>
                <h4 class="card-title text-success" style="font-weight: bold">{% if object.is_active == True %} Activo {% endif %}</h4>
                <h4 class="card-title text-danger" style="font-weight: bold">{% if object.is_active == False %} Inactivo {% endif %}</h4>
                <a href="{% url 'user:user_update' object.id %}" class="btn btn-rose btn-round">Editar</a>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            $('.btnTest').on('click', function () {
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {
                });
            });
        });

    </script>
{% endblock %}

core/user/templates/list_user.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'js/list.js' %}"></script>
{% endblock %}

{% block card_header %}
    <div class="card-header card-header-rose card-header-icon">
        <div class="card-icon">
            <i class="material-icons">people_alt</i>
        </div>
        <h4 class="card-title" style="font-weight: bold">{{ entity }}</h4>
    </div>
{% endblock %}

{% block columns %}
    <th class="text-md-center" style="width:5%"></th>
    <th class="text-md-center" style="width:22%">Nombre Completo</th>
    <th class="text-md-center" style="width:10%">Usuario</th>
    <th class="text-md-center" style="width:16%">Cargo</th>
    <th class="text-md-center" style="width:10%">Roles</th>
    <th class="text-md-center" style="width:20%">Email</th>
    <th class="text-md-center" style="width:9%">Estado</th>
    <th class="text-md-center" style="width:7%">Editar</th>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}


{% endblock %}

core/user/templates/profile.html
{% extends 'body.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
    <script src="{% static 'lib/materialkitpro/js/jquery-3.1.1.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="col-md-9">
        <div class="card">
            <div class="card-header card-header-icon" data-background-color="rose">
                <i class="material-icons">assignment_ind</i>
            </div>
            <div class="card-content">
                <h4 class="card-title" style="font-weight: bold">{{ entity }} - {{ object.username }}</h4>
                    <div class="card-content">
                        <div class="row">
                            <div class="col-md-4">
                                <p class="card-text"><strong>N° Identificación:</strong></p>{{ object.cedula }}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>N° Celular:</strong></p>{{ object.cellphone }}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>E-mail:</strong></p>{{ object.email }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-4">
                                <p class="card-text"><strong>E-mail Personal:</strong></p>
                                {% if object.email_person == None %}
                                    Sin Registro
                                {% else %}
                                    {{ object.email_person }}
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>Fecha de Nacimiento:</strong></p>
                                {% if object.date_birth == None %}
                                    Sin Registro
                                {% else %}
                                    {{ object.date_birth}}
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>Dirección:</strong></p>
                                {% if object.address_user == None %}
                                    Sin Registro
                                {% else %}
                                    {{ object.address_user }}
                                {% endif %}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-4">
                                <p class="card-text"><strong>Fecha de Creación:</strong></p>{{ object.date_joined | date:'Y-m-d' }}
                            </div>
                            <div class="col-md-4">
                                <p class="card-text"><strong>Ultima Sesión:</strong></p>
                                {% if object.last_login == None %}
                                    Sin Registro de Ingreso
                                {% else %}
                                    {{ object.last_login | date:'Y-m-d H:m'}}
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <a href="{% url 'user:change_password' %}" class="btn btn-rose btn-round">Cambiar Contraseña</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card card-profile">
            <div class="card-avatar">
                <a href="#">
                    {% if user.photo %}
                        <img class="img" src="{{ user.photo.url }}" alt="bpmpro_user"/>
                    {% else %}
                        <img class="img" src="{% static 'lib/materialkitpro/img/../../../static/lib/material-dashboard-pro-html-v2.2.2/assets/img/default-avatar.png' %}" alt="bpmpro_user"/>
                    {% endif %}
                </a>
            </div>
            <div class="card-content">
                <h6 class="category text-gray">{{ object.cargo }}</h6>
                <h4 class="card-title">{{ object.get_full_name }}</h4>
                <a href="{% url 'user:user_profile_update' object.id %}" class="btn btn-rose btn-round">Editar</a>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            $('.btnTest').on('click', function () {
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {
                });
            });
        });

    </script>
{% endblock %}